name: bygger docker image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t "hello-python" ./test
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
        context: ./test
        file: ./test/dockerfile
        platforms: ${{ matrix.platforms }}
        push: true
        outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image
